package br.com.java.pcbuild.enums;

public enum CaseTypeEnum {

    ATX_DESKTOP,
    ATX_FULL_TOWER,
    ATX_MID_TOWER,
    ATX_MINI_TOWER,
    ATX_TEST_BENCH,
    HTPC,
    MICROATX_DESKTOP,
    MICROATX_MID_TOWER,
    MICROATX_MINI_TOWER,
    MICROATX_SLIM,
    MINI_ITX_DESKTOP,
    MINI_ITX_TEST_BENCH,
    MINI_ITX_TOWER

}
